# Generated by Django 4.1.3 on 2023-01-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50, verbose_name='adı')),
                ('soyad', models.CharField(max_length=50, verbose_name='soy adı')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='lisans_kod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lisans', models.CharField(max_length=150, verbose_name='Lisans Kodu')),
            ],
        ),
    ]
