# Generated by Django 4.1.3 on 2023-01-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kullanici',
        ),
    ]
