# Generated by Django 4.1.3 on 2023-01-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0002_delete_kullanici'),
    ]

    operations = [
        migrations.CreateModel(
            name='kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50, verbose_name='adı')),
                ('soyad', models.CharField(max_length=50, verbose_name='soy adı')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('username', models.CharField(max_length=50, verbose_name='kullanıcı adı')),
                ('telno', models.IntegerField(verbose_name='telefon numaras')),
                ('odeme', models.BooleanField(verbose_name='ödeme yaptı mı?')),
            ],
        ),
    ]
