# Generated by Django 4.1.3 on 2023-01-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0004_delete_kullanici'),
    ]

    operations = [
        migrations.CreateModel(
            name='kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50, verbose_name='adı')),
                ('soyad', models.CharField(max_length=50, verbose_name='soy adı')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('username', models.CharField(max_length=50, verbose_name='kullanıcı adı')),
                ('telno', models.CharField(max_length=50, verbose_name='telefon no')),
                ('odeme', models.BooleanField(verbose_name='ödeme yaptı')),
                ('lisans', models.CharField(max_length=50, verbose_name='lisans kodu')),
            ],
        ),
        migrations.CreateModel(
            name='menuDuzen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=20, verbose_name='menü adı')),
            ],
        ),
        migrations.CreateModel(
            name='portalgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(max_length=200, upload_to=None, verbose_name='protalgo yükleme dosyası')),
            ],
        ),
        migrations.CreateModel(
            name='sayfaDuzenleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anayazi', models.CharField(max_length=200, verbose_name='yazılacak yazı')),
            ],
        ),
    ]
