# Generated by Django 4.1.3 on 2023-02-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0005_kullanici_menuduzen_portalgo_sayfaduzenleme'),
    ]

    operations = [
        migrations.CreateModel(
            name='geciciKullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50, verbose_name='adı')),
                ('soyad', models.CharField(max_length=50, verbose_name='soy adı')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('username', models.CharField(max_length=50, verbose_name='kullanıcı adı')),
                ('telno', models.CharField(max_length=50, verbose_name='telefon no')),
                ('odeme', models.BooleanField(verbose_name='onaylandı')),
            ],
        ),
        migrations.CreateModel(
            name='kullaniciPaneli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('kullaniciadi', models.CharField(max_length=50, verbose_name='kullanıcı adı')),
                ('parola', models.CharField(max_length=25, verbose_name='parola')),
            ],
        ),
    ]
